import { Employee, Task } from './types';

export const mockEmployees: Employee[] = [
  {
    _id: 'ava.martinez@example.com',
    name: 'Ava Martinez',
    email: 'ava.martinez@example.com',
    role: 'manager',
    department: 'Product',
    status: 'active',
    skills: ['Leadership', 'Roadmapping', 'Stakeholder Communication'],
    avatarUrl: 'https://i.pravatar.cc/150?img=56',
    location: 'Sydney',
    joinedAt: '2021-03-12',
    bio: 'Product leader with a passion for user-centric design.',
  },
  {
    _id: 'ravi.shah@example.com',
    name: 'Ravi Shah',
    email: 'ravi.shah@example.com',
    role: 'employee',
    department: 'Engineering',
    status: 'active',
    skills: ['React', 'TypeScript', 'Node.js'],
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    location: 'Melbourne',
    joinedAt: '2022-07-01',
    bio: 'Frontend engineer focused on performance and DX.',
  },
  {
    _id: 'sofia.petrova@example.com',
    name: 'Sofia Petrova',
    email: 'sofia.petrova@example.com',
    role: 'employee',
    department: 'Design',
    status: 'on-leave',
    skills: ['Figma', 'Motion Design', 'Design Systems'],
    avatarUrl: 'https://i.pravatar.cc/150?img=22',
    location: 'Brisbane',
    joinedAt: '2020-11-20',
    bio: 'Designing delightful experience for enterprise apps.',
  },
];

export const mockTasks: Task[] = [
  {
    _id: 'task-1',
    title: 'Q4 OKR Planning',
    description: 'Facilitate cross-functional alignment session.',
    assignedTo: 'ava.martinez@example.com',
    dueDate: '2025-12-05',
    status: 'in-progress',
    priority: 'high',
    tags: ['planning', 'okr'],
    progress: 60,
  },
  {
    _id: 'task-2',
    title: 'UI Library Audit',
    description: 'Document existing component gaps before redesign.',
    assignedTo: 'ravi.shah@example.com',
    dueDate: '2025-11-29',
    status: 'todo',
    priority: 'medium',
    tags: ['design', 'audit'],
    progress: 10,
  },
  {
    _id: 'task-3',
    title: 'Motion Study',
    description: 'Explore subtle motion cues for dashboard transitions.',
    assignedTo: 'sofia.petrova@example.com',
    dueDate: '2025-12-15',
    status: 'blocked',
    priority: 'low',
    tags: ['research'],
    progress: 35,
  },
];

